source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.3yakj.com/TPT_iOS/TPTSpecs.git'


use_frameworks!

platform :ios, '12.0'

target 'TPTUIGeneralMoudle_Example' do
  pod 'TPTUIGeneralMoudle', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']

  target 'TPTUIGeneralMoudle_Tests' do
    inherit! :search_paths
  end
end



plugin 'cocoapods-pod-sign'
skip_pod_bundle_sign # 用来跳过Xcode对bundle资源的签名



## CocoaPods Hook

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end


pre_install do |installer|
  # form https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
